### PR TITLE
WIP: Introduce sanity check for descriptions, tooltips, Tinkers staging and Utils

### PR DESCRIPTION
**Pull request by kereis**
See #4466.

### CODE REVIEW

**Comment by sam-kirby** [comment]
Thank you for the PR, though I do not think in its current state this should be merged in.

This PR allows things to silently fail. This can result in bugs that would otherwise be caught immediately in testing to slip through.

A hard fail is much preferred in this environment than a silent fail.

**Comment by kereis** [comment]
Well, I guess I can agree with this one, but why does the Environmental Tech part fail out of the box? I think this should be fixed as it looks like any other scripts won't execute when there's a hard fail?

**Comment by sam-kirby** [comment]
Screenshot 2021-01-07 at 12 37 02

I do not see any errors in crafttweaker's log during pack loading on v3.2.1.

As you can see above, the tooltips are correctly applied to e.g. the void ore miner tier 5, and the resource IDs exist in the game. Are you sure this isn't caused by a change you made?

**Comment by kereis** [comment]
I've reinstalled the server by downloading a new server pack from CurseForge. ~~It could be that the previous server instance whose data was copied onto the server by a teammate is faulty.~~ I read that the ATLauncher one does not work the same as the CurseForge one. Environmental Tech errors and such have disappeared.

Currently, the only problem that's left is without using the "fixes" and simply adding NuclearCraft and EnderIO, `Tinkers.zs` throws NPEs as there are no stages defined for the materials that come with each mod. Is this expected? What would be the easiest way to fix that? Something that I have in mind:
- Adding each new material to a stage. However, that can be tedious if the amount of newly added material is huge.
- Individual fix in `Tinkers.zs` like https://github.com/DarkPacks/SevTech-Ages/blob/44611252095e62e43d2cdc1977673fdf83bdd093/src/scripts/crafttweaker/staging/tinkers.zs#L267 (commented code, without changing `Utils.zs`)

I think at the end this PR and issue #4466 can be closed, as this is rather an individual problem (by adding mods of own choice to modpack that were not shipped with out-of-the-box).

**Comment by sam-kirby** [comment]
Apologies for not getting back to you sooner. The best thing to do when adding a new mod is to properly stage it and its components; items, recipes and materials.

To quickly stage items and recipes, pick a stage you want the mod to unlock at, and then add it to this file: https://github.com/DarkPacks/SevTech-Ages/blob/master/original/src/scripts/crafttweaker/staging/itemsAndRecipes/modId.zs

Materials still have to be listed individually, but most mods only add a handful.

You can get a list of all materials using the command `/tcondump materials`.

If you really don't care about staging though, the changes you've made in your branch will result in errors being ignored, and the mods you add will just be available from the beginning of the game.

**Pull request closed without merging**
