### PR TITLE
fix: BlockHarvestDropEvent drop array now takes weighted item stacks

### LINKED ISSUE #3673: Various blocks from PrimalCore drop nothing when broken
## Bug Report

Dried Mud and the following stone types from PrimalCore don't drop anything when broken:

*Common
*Sarson
*Bluestone
*Ortho
*Greenschist
*Blueschist
*Desiccated
*Soul
*Scoria
*Porphyry
*Purpurite
*Ferocalcite
*Carbonite
*Nether
*Eroded End
*Hornblend

## Expected Behaviour

The different types of stone should drop their cobble variants (except dried mud, which should drop itself).

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_201
* Launcher Used: MultiMC
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

Edit: Fixed Java version

### PR DESCRIPTION
**Pull request by sk2048**
* This allows for drop chance to be specified
* Set drop chance to 100%, but open to changes

Closes #3673

### CODE REVIEW

**Comment by sk2048** [comment]
For reference: https://github.com/CraftTweaker/CraftTweaker/commit/b8fa1f55795d442025a64e7e115a1fda198f49c8

**Comment by justinrusso** [comment]
I like the change, but does this actually resolve #3673? Seems odd to be the case if so, as by default it would be a 100% drop prior to this change...

**Comment by sk2048** [comment]
Yes, as the drops array expects WeightedItemStacks you can't set it equal to an array of IItemStacks. Doing this throws an exception, which is printed in the CraftTweaker log, and results in no items being dropped.

**Comment by sk2048** [comment]
```[SERVER_STARTED][SERVER][ERROR] crafttweaker.mc1120.item.MCItemStack cannot be cast to crafttweaker.api.item.WeightedItemStack
java.lang.ClassCastException: crafttweaker.mc1120.item.MCItemStack cannot be cast to crafttweaker.api.item.WeightedItemStack
	at crafttweaker.mc1120.events.handling.MCBlockHarvestDropsEvent.setDrops(MCBlockHarvestDropsEvent.java:45)
	at ZenClassCrafttweakercrafttweaker\events\BlockBreak19.handle(Unknown Source)
	at ZenClassCrafttweakercrafttweaker\events\BlockBreak19.handle(Unknown Source)
        ...

**Pull request merged**
