### PR TITLE
Fixed "Broken" tooltip from displaying on the Cyclic swords

### PR DESCRIPTION
**Pull request by monodemono**

### CODE REVIEW

**Comment by justinrusso** [comment]
There are plenty of other issues, I believe a good handful of Blood Magic for example. But since this PR is titled specifically for Cyclic, it should be good. I'll give it a test later to be sure.

**Comment by monodemono** [comment]
Oh jeez, I'm sorry for all the extra changes I made here. I was trying to learn how to do a few things on Git Kraken, and I just noticed that they're spilling over to here.

**Comment by monodemono** [comment]
Okay, I'm starting to get a hang of this Kraken thing, I've reverted to how it was when I made this pull request, and I'm going to stage my future changes to branches so as not to mess up pull requests in the future. Apologies again for that mix-up earlier.

**Comment by artdude543** [comment]
The changelog needs updating as now it's causing a conflict. You know how to do this? If not I'll handle the update/merge for ya.

**Pull request merged**
